version: '3.8'

services:
  go-server:
    container_name: go-server
    build:
      context: ../
      dockerfile: ./setup/Dockerfile
      args:
        PARALLEL_BATCH: 2
        SEQUENTIAL_BATCH: 20
        NATS_SERVERS: "nats://13.233.167.108:4222,nats://13.127.160.94:4222,nats://13.234.110.245:4222,nats://13.235.245.159:4222,nats://52.66.214.53:4222"
    #command: "tail -f /dev/null"
    ports:
      - 9999:9999
    volumes:
      - './durationMetrics:/tmp/'